CONSTS = {
    "geoMod": {
        "GeoMeta": [
            # "nx_global",
            # "ny_global",
            # "nx_global_elem",
            # "ny_global_elem",
            # "dx_meters",
            # "dy_meters",
            # "latitude_grid",
            # "longitude_grid",
            # "element_ids",
            # "element_ids_global",
            # "latitude_grid_elem",
            # "longitude_grid_elem",
            # "lat_bounds",
            # "lon_bounds",
            # "mesh_inds",
            # "mesh_inds_elem",
            # "height",
            # "height_elem",
            # "sina_grid",
            # "cosa_grid",
            "nodeCoords",
            "centerCoords",
            "inds",
            # "slope",
            # "slp_azi",
            # "slope_elem",
            # "slp_azi_elem",
            # "esmf_grid",
            "esmf_lat",
            "esmf_lon",
        ],
        "handle_exception": {
            "esmf_nc": "Unable to open spatial metadata file: :::arg:::",
        },
        "UnstructuredGeoMeta": [
            "x_lower_bound",
            "x_upper_bound",
            "y_lower_bound",
            "y_upper_bound",
            "dx_meters",
            "dy_meters",
            "element_ids",
            "element_ids_global",
            "sina_grid",
            "cosa_grid",
            "esmf_lat",
            "esmf_lon",
        ],
        "HydrofabricGeoMeta": [
            "nx_local_elem",
            "ny_local_elem",
            "x_lower_bound",
            "x_upper_bound",
            "y_lower_bound",
            "y_upper_bound",
            "nx_global_elem",
            "ny_global_elem",
            "dx_meters",
            "dy_meters",
            "mesh_inds_elem",
            "height_elem",
            "sina_grid",
            "cosa_grid",
            "slope_elem",
            "slp_azi_elem",
            "esmf_lat",
            "esmf_lon",
        ],
        "GriddedGeoMeta": [
            "nx_local_elem",
            "ny_local_elem",
            "nx_global_elem",
            "ny_global_elem",
            "element_ids",
            "element_ids_global",
            "lat_bounds",
            "lon_bounds",
            "mesh_inds",
            "mesh_inds_elem",
            "height_elem",
            "slope_elem",
            "slp_azi_elem",
        ],
    },
}
