name: simulated_swe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - netcdf4
  - xarray
  - numpy
  - matplotlib
  - cartopy
  - geopandas>=0.10.0
  - fiona>=1.9.0
  - fsspec
  - h5netcdf
